name: Go ooxx CI

on:
  push:
    branches:
      - ooxxFeature
  pull_request:
    branches:
      - ooxx

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: ooxx/
